=== nextflow-io/nf-schema/src/testResources/samplesheet_schema_deeply_nested.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/test/test/master/assets/schema_input.json",
    "title": "Test schema for samplesheets",
    "description": "Schema for the file provided with params.input",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "map": {
                "type": "object",
                "properties": {
                    "arrayTest": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }, 
                    "stringTest": {
                        "type": "string"
                    },
                    "numberTest": {
                        "type": "number"
                    },
                    "integerTest": {
                        "type": "integer"
                    },
                    "fileTest": {
                        "type": "string",
                        "format": "file-path"
                    },
                    "mapMeta": {
                        "type": "string",
                        "meta": "mapMeta"
                    }
                }
            },
            "array": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "arrayInArray": {
                "type": "array",
                "items": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "arrayMeta": {
                "type": "array",
                "meta": ["arrayMeta", "otherArrayMeta"],
                "items": {
                    "type": "string"
                }
            },
            "value": {
                "type": "string"
            },
            "meta": {
                "type": "string",
                "meta": "meta"
            },
            "metaMap": {
                "type": "object",
                "meta": "metaMap",
                "properties": {
                    "entry1": {
                        "type": "string"
                    },
                    "entry2": {
                        "type": "number"
                    }
                }
            }
        }
    }
}

=== nextflow-io/nf-schema/src/testResources/deeply_nested.json
[
    {
        "map": {
            "arrayTest": [
                "string1",
                "string2"
            ],
            "stringTest": "string3",
            "numberTest": 1,
            "integerTest": 1,
            "fileTest": "file1.txt",
            "mapMeta": "this is in a map"
        },
        "array": [
            "string4",
            "string5",
            "string6"
        ],
        "arrayInArray": [
            [ "string7", "string8" ],
            [ "string9", "string10" ]
        ],
        "arrayMeta": [
            "metaString45",
            "metaString478"
        ],
        "value": "test",
        "meta": "metaValue",
        "metaMap": {
            "entry1": "entry1String",
            "entry2": 12.56
        }
    }
]
